version: "3.0"

services:
  db:
    image: mysql:8.0.17
    container_name: root
    environment:
      MYSQL_ROOT_PASSWORD: tlstjdals1
      MYSQL_USER: root
      MYSQL_PASSWORD: tlstjdals1
      MYSQL_DATABASE: News_DB
    ports: 
      - 3306:3306
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    volumes:
          - /Users/Shared/data/mysql-test:/var/lib/mysql
    restart: always
  app:
    build: .
    container_name: demo:0.0.1-SNAPSHOT
    image: openjdk:11
    ports:
      - "8880:8080"
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
        - db
    restart: always